### ISSUE TITLE
Error in the function VDJ_call_MIXCR

### ISSUE THREAD

**Issue by Andy-ChanKP** [alexyermanos/Platypus#23]
Hi Victor and Alex, 

I encountered this error when trying to run MIXCR, and I think the error stems from some in-built codes that use "paste". I think if you guys push a change of the code to paste0, that might have solved the issue. This is just my speculations - do you know why else I am encountering this error? I can open the MIXCR menu no problem in the cluster/linux - so I got it installed correctly with a proper license. 

<img width="529" alt="image" src="https://user-images.githubusercontent.com/72179109/187290421-c029b3e5-514a-4d30-85b9-c08493822d4d.png">

Current code: 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/72179109/187290955-385b3575-e4d4-49e1-b553-eb073c85dbe2.png">

If using paste0: 
<img width="438" alt="image" src="https://user-images.githubusercontent.com/72179109/187290890-c70cd2e7-3f99-40df-a747-61faff553e2e.png">

Best, 
Andy

**Comment by vickreiner** [comment]
Hi Andy,
I just pushed a new version of the function with two changes:
1. paste is now paste0
2. I made the java -jar initial call a customizable string (new parameter: custom.cmd.call) In case of any issues with calling Mixcr this may help in the future. 

Please let me know if this helped!
Thanks!

**Comment by Andy-ChanKP** [comment]
Hi Victor, 

Thank you for your help!!! The customizable string is a good idea - so people can specify their java path! But the error persists... 

I am thinking whether the issue might be due to my infrastructure than the codes themselves - I am running R studio on my cluster, and for some reasons, java couldn't be found (I also tried to specify the path to java, like "/usr/share/java", but still without luck. 

Any suggestions would be appreciated - would be nice to calculate the SHM rate with mixcr. 

Many thanks, 
Andy

<img width="616" alt="image" src="https://user-images.githubusercontent.com/72179109/187392013-63815d4d-f5f4-477c-afd5-5bdb359f3995.png">

**Comment by vickreiner** [comment]
Hi!
Can you leave the custom.cmd.call blank ("") and try to call MIXCR without invoking Java first. Depending on your MIXCR installation this may work.
Otherwise I would try to use a terminal on your cluster to find a command that can reliably call mixcr and then translate that into the R function using the custom.cmd.call.
