### ISSUE TITLE
Issue about VDJ_VJ_usage_circos

### ISSUE THREAD

**Issue by wangsiling123** [alexyermanos/Platypus#8]
Hi, this package is powerful. I wonder how to display the labels of each germline genes (V/D/J), not only clonal frequency, when using VDJ_VJ_usage_circos.

**Comment by raphkuhn** [comment]
Hi
We are very happy you are using Platypus for your analysis! 
The labels should always be displayed in the circos plots. There was a bug which prevented the labels to be plotted in older platypus versions. In the newest version this error was fixed and the labels should be displayed. 
Thanks for reporting this bug!

**Comment by wangsiling123** [comment]
Hi:
&nbsp; &nbsp;It seems that the bug still was not fixed, when I performed the newest version (3.3.3).




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alexyermanos/Platypus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月24日(星期四) 凌晨0:20
***@***.***&gt;;
抄送:&nbsp;"王思令 厦门大学 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alexyermanos/Platypus] Issue about VDJ_VJ_usage_circos (Issue #8)





 
Hi
 We are very happy you are using Platypus for your analysis!
 The labels should always be displayed in the circos plots. There was a bug which prevented the labels to be plotted in older platypus versions. In the newest version this error was fixed and the labels should be displayed.
 Thanks for reporting this bug!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vickreiner** [comment]
Hi! 
This should be fixed now in the current 3.3.6 version. Please install this directly from Github. It will be on CRAN soon.
Thank you!
